---

- name: Add User api config into app_configurations
  ansible.builtin.set_fact:
    app_configurations:
      "{{ app_configurations | combine({'user': app_api_user}) }}"
  tags: configuration
  when: app_api_enable

- name: Add Admin api config into app_configurations
  ansible.builtin.set_fact:
    app_configurations:
      "{{ app_configurations | combine({'admin': app_api_admin}) }}"
  tags: configuration
  when: app_api_enable

- name: Add Jobs config into app_configurations
  ansible.builtin.set_fact:
    app_configurations:
      "{{ app_configurations | combine({'jobs': app_jobs}) }}"
  tags: configuration
  when: app_jobs_enable

- name: Add Jobs config into app_configurations.pension
  ansible.builtin.set_fact:
    app_configurations:
      "{{ app_configurations | combine({'pension': app_configurations.pension | combine({'jobs': app_pension_jobs})}) }}"
  tags: configuration
  when: app_jobs_enable

- name: Copy config files
  ansible.builtin.copy:
    src: config/
    dest: "{{ app_config_path }}"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: "0640"
  notify: restart pension
  tags: installation
  no_log: true

- name: Copy config.json
  ansible.builtin.template:
    src: "config/config.json.j2"
    dest: "{{ app_config_path }}/config.json"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: "0640"
  notify: restart pension
  tags: configuration
  no_log: true

- name: AWS credentials config
  ansible.builtin.include_role:
    name: inqwise.common.aws_utils
    tasks_from: config
  vars:
    aws_config_region: "{{ ec2_instance.region }}"
    aws_access_key_id: "{{ app_filesystem_aws.access_key }}"
    aws_secret_access_key: "{{ app_filesystem_aws.secret_access_key }}"
  tags: configuration
