---

- name: Add User api config into app_configurations
  ansible.builtin.set_fact:
    app_configurations:
      "{{ app_configurations | combine({'user': app_api_user}) }}"
  tags: configuration
  when: app_api_enable

- name: Add Admin api config into app_configurations
  ansible.builtin.set_fact:
    app_configurations:
      "{{ app_configurations | combine({'admin': app_api_admin}) }}"
  tags: configuration
  when: app_api_enable

- name: Add Jobs config into app_configurations
  ansible.builtin.set_fact:
    app_configurations:
      "{{ app_configurations | combine({'jobs': app_jobs}) }}"
  tags: configuration
  when: app_jobs_enable

- name: Display app_configurations.jobs
  debug:
    msg: "app_configurations.jobs: {{ app_configurations.jobs }}"
  tags: debug
  when: app_jobs_enable

- name: Set app_pension_jobs configuration with predefined variables
  tags: configuration
  when: app_jobs_enable and app_jobs_auto_sync_in_enable
  ansible.builtin.set_fact:
    app_pension_jobs: "{{ app_pension_jobs | default({}) | combine({
      'fill_queue_interval_in_seconds': app_pension_jobs_fill_queue_interval_in_seconds,
      'process_queue_package_interval_in_seconds': app_pension_jobs_process_queue_package_interval_in_seconds}) }}"
  
- name: Display app_pension_jobs
  debug:
    msg: "app_pension_jobs: {{ app_pension_jobs }}"
  tags: debug
  when: app_jobs_enable and app_jobs_auto_sync_in_enable

- name: Add Jobs config into app_configurations.pension
  ansible.builtin.set_fact:
    app_configurations:
      "{{ app_configurations | combine({'pension': app_configurations.pension | combine({'jobs': app_pension_jobs})}) }}"
  tags: configuration
  when: app_jobs_enable

- name: Display app_configurations.pension.jobs
  debug:
    msg: "app_configurations.pension.jobs: {{ app_configurations.pension.jobs }}"
  tags: debug
  when: app_jobs_enable

- name: Copy config files
  ansible.builtin.copy:
    src: config/
    dest: "{{ app_config_path }}"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: "0640"
  notify: restart pension
  tags: installation

- name: Copy config.json
  ansible.builtin.template:
    src: "config/config.json.j2"
    dest: "{{ app_config_path }}/config.json"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: "0640"
  notify: restart pension
  tags: configuration
  no_log: "{{ 'all' not in ansible_run_tags and 'debug' not in ansible_run_tags }}"

- name: Copy cluster.xml
  ansible.builtin.template: 
    src: 'config/cluster.xml.j2'
    dest: '{{ app_config_path }}/cluster.xml'
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: "0640"
  notify: restart pension
  tags: configuration
  no_log: "{{ 'all' not in ansible_run_tags and 'debug' not in ansible_run_tags }}"

- name: AWS credentials config
  ansible.builtin.include_role:
    name: inqwise.common.aws_utils
    tasks_from: config
  vars:
    aws_config_region: "{{ ec2_instance.region }}"
    aws_access_key_id: "{{ app_filesystem_aws.access_key }}"
    aws_secret_access_key: "{{ app_filesystem_aws.secret_access_key }}"
  tags: configuration
