---
- name: AWS role
  ansible.builtin.import_role:
    name: inqwise.common.aws
  vars:
    dns_record_list:
    - name: "{{ private_dns }}.{{ private_domain }}"
      zone: "{{ private_domain }}"
      type: A
      value: "{{ private_ip }}"
      private: true
      ttl: 120
    tags_facts:
      private_dns: "private_dns"
      jobs_enable: "app_jobs_enable"
      api_enable: "app_api_enable"
      app_name: "app_name"
      logger_filename: "app_logger_filename"
      marketing_mock: "app_marketing_mock" 

- name: Java role
  ansible.builtin.include_role:
    name: inqwise.common.java
  tags: installation

- name: Pension role 
  ansible.builtin.import_role:
    name: pension
   