---
- name: AWS role
  ansible.builtin.import_role:
    name: inqwise.common.aws
  vars:
    dns_record_list:
    - name: "{{ private_dns }}.{{ private_domain }}"
      zone: "{{ private_domain }}"
      type: A
      value: "{{ private_ip }}"
      private: true
      ttl: 120
    tags_facts:
      private_dns: "private_dns"
      jobs_enable: "app_jobs_enable"
      jobs_auto_sync_in_enable: "app_jobs_auto_sync_in_enable"
      api_enable: "app_api_enable"
      app_name: "app_name"
      logger_filename: "app_logger_filename"
      marketing_mock: "app_marketing_mock"
      cluster_name: "cluster_name"
      access_header_name: "app_api_admin_access_header_name"
      webhook_key: "webhook_key"
      telegraf_name: "telegraf_name"

- name: Debuging pension_app_name
  ansible.builtin.debug:
    var: pension_app_name
  tags: debug

- name: Java role
  ansible.builtin.include_role:
    name: inqwise.common.java
  tags: installation

- name: Pension role 
  ansible.builtin.import_role:
    name: pension
  vars:
    discord_webhook: "{{ discord_webhooks[webhook_key | default('apilog')] | default(discord_webhooks.default) }}"
    hz_outbound_ports_range: "{{ cluster_ports_range | default('33000-33500') }}"
    hz_ec2:
      tag_key: "cluster_name"
      tag_value: "{{ cluster_name }}"
      iam_role: "{{ aws_iam_role }}"

- name: Install Alloy
  ansible.builtin.include_role:
    name: alloy
  tags: always
  vars:
    alloy_user_groups:
      - systemd-journal
      - "{{ app_group }}"
    config: |
      loki.write "local" {
        endpoint {
          url = "{{ loki_base_url }}/loki/api/v1/push"
        }
      }

      loki.relabel "journal" {
        forward_to = []

        rule {
          source_labels = ["__journal__systemd_unit"]
          regex         = "(pension.service|telegraf.service)"
          action        = "keep"
        }
        rule {
          source_labels = ["__journal__systemd_unit"]
          target_label  = "unit"
        }
        rule {
          source_labels = ["__journal__hostname"]
          target_label  = "instance"
        }
      }

      loki.source.journal "read" {
        forward_to = [
          loki.write.local.receiver,
        ]
        relabel_rules = loki.relabel.journal.rules
        labels = {
          "app" = "{{ app_name }}",
        }
      }

      local.file_match "local_files" {
        path_targets = [{"__path__" = "/data/pension/logs/*.log"}]
        sync_period = "10s"
      }

      loki.source.file "log_scrape" {
        targets    = local.file_match.local_files.targets
        forward_to = [loki.process.filter_logs.receiver]
        tail_from_end = true
      }
      loki.process "filter_logs" {
        stage.multiline {
          firstline = "^(?P<timestamp>[0-9\\-]{10} [0-9:]{8},[0-9]{3}) (?P<level>[^ ]+)"
        }
        stage.regex {
          expression = "^(?P<timestamp>[0-9\\-]{10} [0-9:]{8},[0-9]{3}) (?P<level>[^ ]+) (?P<logger>[^ ]+) \\[(?P<thread>[^\\]]+)\\] (?P<message>.*)$"
        }
        stage.labels {
          values = {
            "level" = "level",
            "logger" = "logger",
            "timestamp" = "timestamp",
          }
        }
        stage.static_labels {
          values = {
            "app" = "{{ app_name }}",
            "unit"= "{{ app_name }}.service",
          }
        }
        forward_to = [
          loki.write.local.receiver,
        ]
      }
   