---

- name: Restart pension
  ansible.builtin.service:
    name: "{{ app_service_name }}"
    state: restarted
    enabled: true
  listen: "restart pension"
  when: app_service_start_and_enable

- name: Check api is started properly
  ansible.builtin.include_tasks: ga-started.yml
  listen: "restart pension"
  when: app_service_start_and_enable and app_api_enable
